;#ADD004BASIC PIEs#
;-| Button Remapping |-----------------------------------------------------
[Remap]
x = x
y = y
z = z
a = a
b = b
c = c
s = s
;-| Default Values |-------------------------------------------------------
[Defaults]
command.time = 15
command.buffer.time = 1

;-| Super Motions |--------------------------------------------------------
[Command]
name="Red Hawk"
command=~D, DF, F, D, DF, F, a
time=32
[Command]
name="Red Hawk"
command=~D, DF, F, D, DF, F, b
time=32
[Command]
name="Red Hawk"
command=~D, DF, F, D, DF, F, c
time=32

[Command]
name="Elephant Gatling"
command=~D, DF, F, D, DF, F, x+z
time=32
[Command]
name="Elephant Gatling"
command=~D, DF, F, D, DF, F, y+z
time=32
[Command]
name="Elephant Gatling"
command=~D, DF, F, D, DF, F, x+y
time=32

[Command]
name="Jet Gatling"
command=~D, DB, B, D, DB, B, x
time=32
[Command]
name="Jet Gatling"
command=~D, DB, B, D, DB, B, y
time=32
[Command]
name="Jet Gatling"
command=~D, DB, B, D, DB, B, z
time=32

[Command]
name="Gear 4 Strike"
command=~D, DF, F, D, DF, F, a+x
time=32
[Command]
name="Gear 4 Strike"
command=~D, DF, F, D, DF, F, b+y
time=32
[Command]
name="Gear 4 Strike"
command=~D, DF, F, D, DF, F, c+z
time=32
;-| Special Motions |------------------------------------------------------
[Command]
name = "qcfz"
command = ~D, DF, F, z
time = 15

[Command]
name = "qcfz"
command = ~D, DF, F, ~z
time = 15


[Command]
name = "Elephant Gun1"
command = ~D, DF, F, x
time = 15
[Command]
name = "Elephant Gun2"
command = ~D, DF, F, y
time = 15
[Command]
name = "Elephant Gun3"
command = ~D, DF, F, z
time = 15
[Command]
name = "Elephant Gun1"
command = ~D, DF, F, ~x
time = 15
[Command]
name = "Elephant Gun2"
command = ~D, DF, F, ~y
time = 15
[Command]
name = "Elephant Gun3"
command = ~D, DF, F, ~z
time = 15

[Command]
name = "Elephant GunEX"
command = ~D, DF, F, x+y
time = 15
[Command]
name = "Elephant GunEX"
command = ~D, DF, F, y+z
time = 15
[Command]
name = "Elephant GunEX"
command = ~D, DF, F, x+z
time = 15

[Command]
name = "Storm1"
command = ~F, D, DF, x
time = 15
[Command]
name = "Storm2"
command = ~F, D, DF, y
time = 15
[Command]
name = "Storm3"
command = ~F, D, DF, z
time = 15
[Command]
name = "Storm1"
command =~F, D, DF, ~x
time = 15
[Command]
name = "Storm2"
command = ~F, D, DF, ~y
time = 15
[Command]
name = "Storm3"
command = ~F, D, DF, ~z
time = 15

[Command]
name = "StormEX"
command = ~F, D, DF, x+y
time = 15
[Command]
name = "StormEX"
command = ~F, D, DF, y+z
time = 15
[Command]
name = "StormEX"
command = ~F, D, DF, x+z
time = 15

[Command]
name = "Jet Pistol1"
command = ~D, DF, F, a
time = 15
[Command]
name = "Jet Pistol2"
command = ~D, DF, F, b
time = 15
[Command]
name = "Jet Pistol3"
command = ~D, DF, F, c
time = 15
[Command]
name = "Jet Pistol1"
command = ~D, DF, F, ~a
time = 15
[Command]
name = "Jet Pistol2"
command = ~D, DF, F, ~b
time = 15
[Command]
name = "Jet Pistol3"
command = ~D, DF, F, ~c
time = 15

[Command]
name = "Jet PistolEX"
command = ~D, DF, F, a+b
time = 15
[Command]
name = "Jet PistolEX"
command = ~D, DF, F, b+c
time = 15
[Command]
name = "Jet PistolEX"
command = ~D, DF, F, a+c
time = 15

[Command]
name = "Jet Bazooka1"
command = ~D, DB, B, x
time = 15
[Command]
name = "Jet Bazooka2"
command = ~D, DB, B, y
time = 15
[Command]
name = "Jet Bazooka3"
command = ~D, DB, B, z
time = 15
[Command]
name = "Jet Bazooka1"
command = ~D, DB, B, ~x
time = 15
[Command]
name = "Jet Bazooka2"
command = ~D, DB, B, ~y
time = 15
[Command]
name = "Jet Bazooka3"
command = ~D, DB, B, ~z
time = 15

[Command]
name = "Jet BazookaEX"
command = ~D, DB, B, x+y
time = 15
[Command]
name = "Jet BazookaEX"
command = ~D, DB, B, y+z
time = 15
[Command]
name = "Jet BazookaEX"
command = ~D, DB, B, x+z
time = 15

[Command]
name = "Ono1"
command = ~D, DB, B, a
time = 15
[Command]
name = "Ono2"
command = ~D, DB, B, b
time = 15
[Command]
name = "Ono3"
command = ~D, DB, B, c
time = 15
[Command]
name = "Ono1"
command = ~D, DB, B, ~a
time = 15
[Command]
name = "Ono2"
command = ~D, DB, B, ~b
time = 15
[Command]
name = "Ono3"
command = ~D, DB, B, ~c
time = 15

[Command]
name = "OnoEX"
command = ~D, DB, B, a+b 
time = 15
[Command]
name = "OnoEX"
command = ~D, DB, B, b+c
time = 15
[Command]
name = "OnoEX"
command = ~D, DB, B, a+c
time = 15

[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, x
time = 16
[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, y
time = 16
[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, z
time = 16
[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, ~x
time = 16
[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, ~y
time = 16
[Command]
name = "412p" ;Zero Counter
command = ~B, DB, D, ~z
time = 16
[Command]
name = "412k" ;Zero Counter
command = ~B, DB, D, a
time = 16
[Command]
name = "412k" ;Zero Counter
command = ~B, DB, D, b
time = 16
[Command]
name=  "412k" ;Zero Counter
command = ~B, DB, D, c
time = 16
[Command]
name = "412k" ;Zero Counter
command = ~B, DB, D, ~a
time = 16
[Command]
name = "412k" ;Zero Counter
command = ~B, DB, D, ~b
time = 16
[Command]
name = "412k" ;Zero Counter
command = ~B, DB, D, ~c
time = 16
;-| Double Tap |-----------------------------------------------------------
[Command]
name = "FF"     ;Required (do not remove)
command = F, F
time = 10

[Command]
name = "BB"     ;Required (do not remove)
command = B, B
time = 10

;-| 2/3 Button Combination |-----------------------------------------------
[Command]
name = "recovery";Required (do not remove)
command = x+y
time = 1
[Command]
name="recovery"
command=a+x
time=1
[Command]
name = "recovery"
command = y+z
time=1
[Command]
name = "recovery"
command = x+z
time=1
[Command]
name = "recovery"
command = a+b
time=1
[Command]
name = "recovery"
command = b+c
time=1
[Command]
name = "recovery"
command = a+c
time=1

[Command]
name = "pp"
command = x+y
time = 1
[Command]
name = "pp"
command = x+z
time = 1
[Command]
name = "pp"
command = y+z
time = 1
[Command]
name = "kk"
command = a+b
time = 1
[Command]
name = "kk"
command = a+c
time = 1
[Command]
name = "kk"
command = b+c
time = 1
[Command]
name = "a+x"
command = a+x
time=1
[Command]
name = "b+y"
command = b+y
time = 1
[Command]
name = "c+z"
command = c+z
time = 1
;-| Single Button |---------------------------------------------------------
[Command]
name = "a"
command = a
time = 1
[Command]
name = "b"
command = b
time = 1
[Command]
name = "c"
command = c
time = 1
[Command]
name = "x"
command = x
time = 1
[Command]
name = "y"
command = y
time = 1
[Command]
name = "z"
command = z
time = 1
[Command]
name = "s"
command = s
time = 1
;-| Single Dir |------------------------------------------------------------
[Command]
name = "fwd" ;Required (do not remove)
command = $F
time = 1
[Command]
name = "downfwd"
command = $DF
time = 1
[Command]
name = "down" ;Required (do not remove)
command = $D
time = 1
[Command]
name = "downback"
command = $DB
time = 1
[Command]
name = "back" ;Required (do not remove)
command = $B
time = 1
[Command]
name = "upback"
command = $UB
time = 1
[Command]
name = "up" ;Required (do not remove)
command = $U
time = 1
[Command]
name = "upfwd"
command = $UF
time = 1
;-| Hold Button |--------------------------------------------------------------
[Command]
name = "hold_x"
command = /x
time = 1
[Command]
name = "hold_y"
command = /y
time = 1
[Command]
name = "hold_z"
command = /z
time = 1
[Command]
name = "hold_a"
command = /a
time = 1
[Command]
name = "hold_b"
command = /b
time = 1
[Command]
name = "hold_c"
command = /c
time = 1
[Command]
name = "hold_s"
command = /s
time = 1
;-| Hold Dir |--------------------------------------------------------------
[Command]
name = "holdfwd";Required (do not remove)
command = /$F
time = 1
[Command]
name = "holdback";Required (do not remove)
command = /$B
time = 1
[Command]
name = "holdup" ;Required (do not remove)
command = /$U
time = 1
[Command]
name = "holddown";Required (do not remove)
command = /$D
time = 1
[Command]
name = "holdfwd" ;Required (do not remove)
command = /$F
time = 1
[Command]
name = "holddownfwd"
command = /$DF
time = 1
[Command]
name = "holddown" ;Required (do not remove)
command = /$D
time = 1
[Command]
name = "holddownback"
command = /$DB
time = 1
[Command]
name = "holdback" ;Required (do not remove)
command = /$B
time = 1
[Command]
name = "holdupback"
command = /$UB
time = 1
[Command]
name = "holdup" ;Required (do not remove)
command = /$U
time = 1
[Command]
name = "holdupfwd"
command = /$UF
time = 1
;---------------------------------------------------------------------------
;Release Direction
[Command]
name = "rlsfwd"
command = ~$F
time = 1
[Command]
name = "rlsback"
command = ~$B
time = 1
[Command]
name = "rlsup"
command = ~$U
time = 1
[Command]
name = "rlsdown"
command = ~$D
time = 1
;--------------------------------------------------------------------------
;Release Button
[Command]
name = "rlsx"
command = ~x
time = 1
[Command]
name = "rlsy"
command = ~y
time = 1
[Command]
name = "rlsz"
command = ~z
time = 1
[Command]
name = "rlsa"
command = ~a
time = 1
[Command]
name = "rlsb"
command = ~b
time = 1
[Command]
name = "rlsc"
command = ~c
time = 1
;---------------------------------------------------------------------------
;Other
[Command]
name = "highjump"
command = $D, $U
time = 15
[Command]
name = "DU"
command = D, U
time = 18
[Command]
name = "DU"
command = DB, UF
time = 18
[Command]
name = "DU"
command = DF, UB
time = 18
[Command]
name = "DU"
command = $D, UF
time = 18
[Command]
name = "DU"
command = $D, UB
time = 18
;---------------------------------------------------------------------------
[Statedef -1]

;##[a4b_-1_start.v20200523]##
;//==========================
;// add004-1-sctrls-start
;//==========================
;--- partner_standby
[state 0]
	type=selfstate
	value=190190
	ctrl=0
	trigger1=ctrl && numpartner && !ishelper && roundstate=2 && pos y=0
	trigger1=(sysfvar(4)>0) && (sysfvar(0)>0) && playeridexist(floor(sysfvar(0)))
	trigger1=(playerid(floor(sysfvar(0))),var(0)=90900) && (playerid(floor(sysfvar(0))),var(22)=4)
	ignorehitpause=1
;##Add.List01##
;//==========================
;// add004-1-sctrls-end
;//==========================
;##[a4b_-1_end]##




[State -1, Tick Fix]
type = CtrlSet
triggerall = !ctrl
trigger1 = (StateNo = 52 || StateNo = 101 || StateNo = 5120) && !AnimTime
trigger2 = (StateNo = [200,499]) && !AnimTime
trigger3 = StateNo = 810 && !AnimTime
trigger4 = (StateNo = 5001 || StateNo = 5011 || StateNo = 151 || StateNo = 153) && HitOver
trigger5 = (StateNo = [700,715]) && !AnimTime
trigger6 = (StateNo = [760,762]) && !AnimTime
value = 1

;-----------------------------------------------------------------
;==================================PARRY COMMAND STATES===================================

[state -1, Parry Times Check]
type= varset
triggerall= numenemy && roundstate=2 && var(12)
triggerall= (stateno!=[760,762]) && stateno!=52
trigger1= ((Ctrl||StateNo=21) && time>20) || movetype!=I
var(12)=0

[State -1, Standing Parry]
type=hitoverride
triggerall= !AIlevel && roundstate=2 && statetype=S
triggerall= command="fwd" && command!="back" && command!="up" && command!="down"
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
trigger1= ctrl || (stateno=[760,761])
trigger1= var(21):=1
attr=SA,AA,AP
stateno=760
slot=0
time=8

[State -1, Crouching Parry]
type=hitoverride
triggerall= !AIlevel && roundstate=2 && statetype!=A
triggerall= command="down" && command!="fwd" && command!="back" && command!="up"
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
trigger1= ctrl || (stateno=[760,761])
trigger1= var(21):=2
attr=C,AA,AP
stateno=761
slot=1
time=9

[State -1, Aereal Parry]
type=hitoverride
triggerall= !AIlevel && roundstate=2 && statetype=A
triggerall= command="fwd" && command!="back" && command!="up" && command!="down"
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
trigger1= ctrl || stateno=762
trigger1= var(21):=3
attr=SCA,AA,AP
stateno=762
forceair=1
slot=2
time=8

[State -1, Standing Parry]
type=hitoverride
triggerall= AIlevel && numenemy
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
triggerall= roundstate=2 && statetype!=A && fvar(39)<=360 && var(21):=1
trigger1= Ctrl || StateNo = 21
trigger1= Random < AIlevel ** 2 / 64.0 * (20 + (LifeMax-Life))
trigger2= ((stateno=[760,761]) || (prevstateno=[760,761]))
trigger2= Random < (160 + (LifeMax-Life)/5 - 8 *(IFElse(var(12)<6,1,var(12))) * (AIlevel ** 2 / 64.0))
trigger3= (prevstateno=[100,105]) && time <= 6
trigger3= random < 200 * (AIlevel ** 2 / 64.0)
attr=SA,AA,AP
stateno=760
slot=0
time=4

[State -1, Crouching Parry]
type=hitoverride
triggerall= AIlevel && numenemy
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
triggerall= roundstate=2 && statetype!=A && fvar(39)<=360 && var(21):=2
trigger1= ((stateno=[760,761]) || (prevstateno=[760,761]))
trigger1= Random < (160 + (LifeMax-Life)/5 - 8 *(IFElse(var(12)<6,1,var(12))) * (AIlevel ** 2 / 64.0))
trigger2= (prevstateno=[100,105]) && time <= 6 && random < 512
trigger3= (stateno=[10,13]) || (((stateno=[5120,5121])||stateno=5200||stateno=5210||stateno=5220)&&!animtime) || (((prevstateno=[5120,5121])||prevstateno=5200||prevstateno=5210||prevstateno=5220)&&(time=[0,6]))
trigger4= Random < AIlevel ** 2 / 64.0 * ifelse(life<250,690,(lifemax-life)/2)
trigger5= (Ctrl||StateNo=21)
trigger5= Random < AIlevel ** 2 / 64.0 * (20 + (LifeMax-Life))
attr=C,AA,AP
stateno=761
slot=1
time=5

[State -1, Aereal Parry]
type=hitoverride
triggerall= AIlevel && numenemy
triggerall= (StateNo!=[120,169]) && (stateno!=[10160,10165])
triggerall= roundstate=2 && statetype=A && fvar(39)<=360
trigger1= (Ctrl||StateNo=21)
trigger1= Random < (AIlevel ** 2 / 64.0 * 360)
trigger1= var(21):=3
trigger2= stateno=762 && time < 17
trigger2= Random < (160 + (LifeMax-Life)/5 - 8 *(IFElse(var(12)<6,1,var(12))) * (AIlevel ** 2 / 64.0))
trigger2= var(21):=3
attr=SCA,AA,AP
stateno=762
forceair=1
slot=2
time=4

[State -1, Reset Standing Parry]
type=hitoverride
triggerall = StateNo!=[760,762]
trigger1= (!(Ctrl||StateNo=21) && (stateno!=[760,761])) || var(20)
trigger2= movetype!=I || (stateno=[100,106])|| (stateno=[120,132])
trigger3= !AIlevel && (command="holdback" || command="holdup")
trigger4= (statetype=S || statetype=C) && var(21) = 3 ;var(21)!=1 && var(21)!=2 && var(21)!=4 && var(21)!=5
trigger5= fvar(39)>360
slot=0
time=0

[State -1, Reset Crouching Parry]
type=hitoverride
triggerall = StateNo!=[760,762]
trigger1= (!(Ctrl||StateNo=21) && (stateno!=[760,761])) || var(20)
trigger2= movetype!=I || (stateno=[100,106])|| (stateno=[120,132])
trigger3= !AIlevel && (command="holdback" || command="holdup")
trigger4= (statetype=S || statetype=C) && var(21) = 3;var(21)!=1 && var(21)!=2 && var(21)!=4 && var(21)!=5
trigger5= fvar(39)>360
slot=1
time=0

[State -1, Reset Aereal Parry]
type=hitoverride
triggerall = StateNo!=[760,762]
trigger1= (!(Ctrl||StateNo=21) && (stateno!=762)) || var(20)
trigger2= movetype!=I
trigger3= !AIlevel && (command="holdback" || command="holdup")
trigger4= statetype=A && var(21)=1 && var(21)=2 && var(21)=4 && var(21)=5
trigger5= fvar(39)>360
slot=2
time=0
;--------------------------------------------------------------------
[State -1, Gear 4 Strike]
type=ChangeState
value=3200
triggerall=!AILevel && RoundState=2 && StateType != A &&var(20)<=0&& power >= 3000&&command ="Gear 4 Strike"
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(6)
;----------------------------------------------------------------------
[State -1, Jet Gatling]
type=ChangeState
value=3100
triggerall=!AILevel && RoundState=2 && StateType != A &&var(20) <= 60 && power >= 1000&&command ="Jet Gatling"
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(6)|| var(7)
;----------------------------------------------------------------------
[State -1, Elephant Gatling]
type=ChangeState
value=3300
triggerall=!AILevel && RoundState=2 && StateType != A &&var(20) <= 60 && power >= 2000&&command ="Elephant Gatling"
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(6)|| var(7)
;----------------------------------------------------------------------
[State -1, Red Hawk]
type=ChangeState
value=3000
triggerall=!AILevel && RoundState=2 && StateType != A &&var(20) <= 60 && power >= 1000&&command ="Red Hawk"
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(6)|| var(7)
;========================================================================
[State -1, Storm]
type=ChangeState
value=Ifelse(command="StormEX"&&var(20) <= 60&&power>=500,1051,1050)
triggerall=!AILevel && RoundState=2 && StateType != A && ((command="Storm1")||(command="Storm2")||(command="Storm3")||(command="StormEX"&&power>=500&&var(20) <= 60))
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(5)
trigger3=(stateno = 450) && movecontact && (command="StormEX"&&power>=500&&var(20) <= 60)
;========================================================================
[State -1, Elephant Gun]
type=ChangeState
value=Ifelse(command="Elephant GunEX"&&var(20) <= 60&&power>=500,1010,1000)
triggerall=!AILevel && RoundState=2 && StateType != A && ((command="Elephant Gun1")||(command="Elephant Gun2")||(command="Elephant Gun3")||(command="Elephant GunEX"&&power>=500&&var(20) <= 60))
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(5)
trigger3=(stateno = 450) && movecontact && (command="Elephant GunEX"&&power>=500&&var(20) <= 60)
;========================================================================
[State -1, Jet Pistol]
type=ChangeState
value=Ifelse(command="Jet PistolEX"&&var(20) <= 60&&power>=500,1025,1020)
triggerall=!AILevel && RoundState=2 && StateType != A && ((command="Jet Pistol1")||(command="Jet Pistol2")||(command="Jet Pistol3")||(command="Jet PistolEX"&&power>=500&&var(20) <= 60))
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(5)
trigger3=(stateno = 450) && movecontact && (command="Jet PistolEX"&&power>=500&&var(20) <= 60)
;========================================================================
[State -1, Jet Bazooka]
type=ChangeState
value=Ifelse(command="Jet BazookaEX"&&var(20) <= 60&&power>=500,1035,1030)
triggerall=!AILevel && RoundState=2 && StateType != A && ((command="Jet Bazooka1")||(command="Jet Bazooka2")||(command="Jet Bazooka3")||(command="Jet BazookaEX"&&power>=500&&var(20) <= 60))
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(5)
trigger3=(stateno = 450) && movecontact && (command="Jet BazookaEX"&&power>=500&&var(20) <= 60)
;========================================================================
[State -1, Ono Kick]
type=ChangeState
value=Ifelse(command="OnoEX"&&var(20) <= 60&&power>=500,1040,1040)
triggerall=!AILevel && RoundState=2 && StateType != A && ((command="Ono1")||(command="Ono2")||(command="Ono3")||(command="OnoEX"&&power>=500&&var(20) <= 60))
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])
trigger2=var(5)
trigger3=(stateno = 450) && movecontact && (command="OnoEX"&&power>=500&&var(20) <= 60)
;========================================================================
[State -1, Zero Counter]
type = ChangeState
value = 750
trigger1 = StateNo = 150 || StateNo = 152
trigger1 = command = "412p" || command = "412k"
trigger1 = !AILevel&&RoundState = 2 && StateType != A
trigger1 = power >= 1000 && !var(20)
;------------------------------------------------------------------------
[State -1, Throw]
type=ChangeState
value =800
trigger1=(command="holdfwd"||command="holdback")&&(command="pp"||command="kk")
trigger1=!AILevel&&RoundState=2 && Statetype!=A && !var(20)
trigger1=ctrl
;------------------------------------------------------------------------
[State -1, Air Throw]
type=Null;ChangeState
value =850
trigger1=(command="holdfwd"||command="holdback")&&(command="pp")
trigger1=!AILevel&&RoundState=2 && Statetype=A && Pos Y<=-30 && !var(20)
trigger1=ctrl
;-------------------------------------------------------------------------
[State -1, Power Charge]
type = ChangeState
value = 730
trigger1 = command = "hold_b" && command = "hold_y"
trigger1 = !AILevel&&RoundState = 2 && StateType != A
trigger1 = power < const(data.power) && power < PowerMax && !var(20)
trigger1 = ctrl || (StateNo = [100,101])
;--------------------------------------------------------------------------
[State -1, Super Jump]
type = ChangeState
value = 123
triggerall= !AILevel && var(55)=2 && roundstate=2 && statetype != A
trigger1 = ctrl && command = "DU" 
trigger2 = stateno=420 && movehit && command = "holdup"
;--------------------------------------------------------------------------
[State -1, SIdestep/Dodge]
type = ChangeState
value = Ifelse(command="holdfwd",710,Ifelse(command="holdback",715,700))
triggerall = command = "a+x"
triggerall = !AILevel && RoundState = 2 && StateType != A
trigger1 = (ctrl || (StateNo = [100,101]))
;--------------------------------------------------------------------------
[State -1, Custom Combo]
type = ChangeState
value = Ifelse(StateType = A,905,900)
triggerAll = !AILevel && command = "c+z" && RoundState = 2 && power >= 1000 && !var(20)
trigger1 = ctrl || StateNo = 52 || (StateNo = [100,101])
trigger1 = !var(41)
;--------------------------------------------------------------------------
[State -1, Run /Dash Back]
type = ChangeState
value = Ifelse(command = "BB",105,100)
trigger1 = !AILevel&&Roundstate=2&&statetype = S
trigger1 = command = "FF"||command = "BB"
trigger1 = ctrl
;--------------------------------------------------------------------------
;--------------------------------------------------------------------------
[State -1, Standing Low Punch]
type=ChangeState
value=200
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="x"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
;---------------------------------------------------------------------------
[State -1, Standing Foward Medium Punch]
type=ChangeState
value=215
triggerall=!AILevel&&Roundstate=2&&statetype != A && Command = "holdfwd" && command="y"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3 = stateno = 100
;---------------------------------------------------------------------------
[State -1, Standing Far/Close Medium Punch]
type=ChangeState
value = 210 + (Abs(P2BodyDist X) <= 15) * 1
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="y"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,209])||(stateno=[230,239])||(stateno=[400,409])||(stateno=[430,439]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Standing High Punch]
type=ChangeState
value=220
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="z"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,219])||(stateno=[230,249])||(stateno=[400,419])||(stateno=[430,449]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Standing Low Kick]
type=ChangeState
value=230
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="a"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=(stateno=[200,209])&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Standing Medium Kick]
type=ChangeState
value=240
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="b"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,219])||(stateno=[230,239])||(stateno=[400,419])||(stateno=[430,439]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Standing High Kick]
type=ChangeState
value=250
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command != "holddown"&& command="c"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,249])||(stateno=[400,449]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching Low Punch]
type=ChangeState
value=400
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command="holddown"&& command="x"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
;---------------------------------------------------------------------------
[State -1, Crouching Medium Punch]
type=ChangeState
value=410
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command= "holddown"&& command="y"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,209])||(stateno=[230,239])||(stateno=[400,409])||(stateno=[430,439]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching High Punch]
type=ChangeState
value=420
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command="holddown"&& command="z"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,219])||(stateno=[230,249])||(stateno=[400,419])||(stateno=[430,449]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching Low Kick]
type=ChangeState
value=430
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command="holddown"&& command="a"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,209])||(stateno=[400,409]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching Medium Kick]
type=ChangeState
value=440
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command="holddown"&& command="b"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,219])||(stateno=[230,239])||(stateno=[400,419])||(stateno=[430,439]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching High Kick]
type=ChangeState
value=450
triggerall=!AILevel&&Roundstate=2&&statetype != A&&command="holddown"&& command="c"
trigger1=ctrl||stateno=[100,101]
trigger2=var(4)
trigger3=((stateno=[200,249])||(stateno=[400,449]))&&movecontact&&var(55)
;---------------------------------------------------------------------------
[State -1, Jumping Low Punch]
type=ChangeState
value=600
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="x"
trigger1=ctrl
trigger2=var(4)
;---------------------------------------------------------------------------
[State -1, Jumping Medium Punch]
type=ChangeState
value=610
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="y"
trigger1=ctrl
trigger2=var(4)
trigger3=((stateno=[600,609])||(stateno=[630,639]))&&movecontact&&var(55)=2
;---------------------------------------------------------------------------
[State -1, Jumping High Punch]
type=ChangeState
value=620
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="z"
trigger1=ctrl
trigger2=var(4)
trigger3=((stateno=[600,619])||(stateno=[630,649]))&&movecontact&&var(55)=2
;---------------------------------------------------------------------------
[State -1, Jumping Low Kick]
type=ChangeState
value=630
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="a"
trigger1=ctrl
trigger2=var(4)
trigger3=(stateno=[600,609])&&movecontact&&var(55)=2
;---------------------------------------------------------------------------
[State -1, Jumping Medium Kick]
type=ChangeState
value=640
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="b"
trigger1=ctrl
trigger2=var(4)
trigger3=((stateno=[600,619])||(stateno=[630,639]))&&movecontact&&var(55)=2
;---------------------------------------------------------------------------
[State -1, Jumping High Kick]
type=ChangeState
value=650
triggerall=!AILevel&&Roundstate=2&&statetype=A&&command="c"
trigger1=ctrl
trigger2=var(4)
trigger3=(stateno=[600,649])&&movecontact&&var(55)=2
;---------------------------------------------------------------------------
[State -1, Taunt]
type = ChangeState
value = 195
triggerall = command = "s"
triggerall = !AILevel&&Roundstate=2&&StateType != A
triggerall = StateNo != [200,699]
trigger1 = ctrl || (StateNo = [100,101])
trigger2 = var(5)
;--------------------------------------------------------------------------
;AI
;--------------------------------------------------------------------------
;-------------------------------------------------------------------
[State -1, Throw]
type = ChangeState
value = 800
triggerall = AILevel&&random < (500 * (AIlevel ** 2 / 64.0))
triggerall = roundstate=2&&statetype!=A&& enemynear,statetype!=L&&(enemynear,stateno!=[5120,5201]) && !var(20)
triggerall = enemynear,movetype!=H&&enemynear,statetype!=A&&enemynear,Hitover&&(p2bodydist x =[0,30])
triggerall = ctrl||stateno=100||stateno=52
trigger1 = random>=800
trigger2 = enemynear,stateno=[120,155]
trigger2 = random>=500
trigger3 = stateno=100
trigger4=(p2bodydist x=[0,30])&&random<250
trigger5=(p2stateno=[120,155])&&(p2bodydist x=[0,30])&&random<500
;-------------------------------------------------------------------
[State -1, Air Throw]
type = Null;ChangeState
value = 850
triggerall = AILevel&&random < (500 * (AIlevel ** 2 / 64.0))
triggerall = roundstate=2&&statetype=A&& enemynear,statetype!=L&&(enemynear,stateno!=[5120,5201]) && !var(20)
triggerall = enemynear,movetype!=H&&enemynear,statetype=A&&enemynear,Hitover&&(p2bodydist x =[0,30])&&(p2bodydist y =[-50,0])
triggerall = ctrl
trigger1 = random>=800
trigger2 = enemynear,stateno=[120,155]
trigger2 = random>=500
trigger3=(p2bodydist x=[0,30])&&random<250
trigger4=(p2stateno=[120,155])&&(p2bodydist x=[0,30])&&random<500
;------------------------------------------------------------------------
[State -1, Standing Low Punch AI]
type = ChangeState
value = 200
triggerall = AILevel && numenemy&&roundstate=2&&StateType != A
triggerall = p2bodydist x <=45&&(p2bodydist y = [-80,5])&&P2statetype != A&&P2statetype != C&&P2statetype != L&& random < (650 * (AIlevel ** 2 / 64.0))
trigger1 = ctrl
trigger2 = (stateno = [100,101]) && random < 100
;---------------------------------------------------------------------------
[State -1, Standing Foward Medium Punch]
type=ChangeState
value=215
triggerall = AILevel && numenemy && roundstate=2 && StateType = S && P2statetype != A && P2statetype != C
triggerall = (p2bodydist x = [5, 40]) && p2statetype != L && !(enemynear, hitfall)
trigger1=ctrl && random < (150 * (AIlevel ** 2 / 64.0))
trigger2 = stateno = 100
;---------------------------------------------------------------------------
[State -1, Standing Far/Close Medium Punch AI]
type=ChangeState
value = 210 + (Abs(P2BodyDist X) <= 15) * 1
triggerall = AILevel && numenemy && roundstate=2 && StateType != A && P2statetype != A && P2statetype != C
triggerall = (p2bodydist x = [0, 30]) && p2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (150 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [200,209])|| (stateno = [230,239])||(stateno = [400,409])||(stateno = [430,439]))&& movehit&&var(55)
trigger2 = random < 350
;---------------------------------------------------------------------------
[State -1, Standing High Punch AI]
type = ChangeState
value = 220
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 55]) && (p2bodydist y = [ -80, 80]) && p2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (80 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [210,219])|| (stateno = [240,249])||(stateno = [410,419])||(stateno = [440,449]))&& movehit&&var(55)
trigger2 = random < 650
;---------------------------------------------------------------------------
[State -1, Standing Low Kick AI]
type = ChangeState
value = 230
triggerall = AILevel && numenemy && roundstate=2 && StateType != A && P2statetype != A
triggerall = (p2bodydist x = [0, 40]) && p2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (80 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [200,209])|| (stateno = [400,409]))&& movehit&&var(55)
trigger2 = random < 200
trigger3 = (stateno = [100,101]) && random < 100
;---------------------------------------------------------------------------
[State -1, Standing Medium Kick AI]
type = ChangeState
value = 240
triggerall = AILevel && numenemy && roundstate=2 && StateType != A && P2statetype != A && P2statetype != C
triggerall = (p2bodydist x = [0, 55]) && p2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (100 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [210,219])|| (stateno = [230,239])||(stateno = [410,419])||(stateno = [430,439]))&& movehit&&var(55)
trigger2 = random < 350
;---------------------------------------------------------------------------
[State -1, Standing High Kick AI]
type = ChangeState
value = 250
triggerall = AILevel && numenemy && roundstate=2 && StateType != A && P2statetype != C
triggerall = (p2bodydist x = [0, 60]) && (p2bodydist y = [ -60, 50]) && p2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (100 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [240,249])|| (stateno = [440,449]))&& movehit && stateno != 225&&var(55)
trigger2 = random < 800
;---------------------------------------------------------------------------
[State -1, Crouching Low Punch]
type = ChangeState
value = 400
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 40]) &&(p2bodydist y = [-50,25]) && P2statetype != A && P2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (100 * (AIlevel ** 2 / 64.0))
trigger2 = stateno = [100,101]
;---------------------------------------------------------------------------
[State -1, Crouching Medium Punch]
type = ChangeState
value = 410
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 55]) &&(p2bodydist y = [-50,25]) && P2statetype != A && P2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (150 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [200,209])|| (stateno = [230,239])||(stateno = [400,409])||(stateno = [430,439]))&& movehit&&var(55)
trigger2 = random < 800
;---------------------------------------------------------------------------
[State -1, Crouching High Punch]
type = ChangeState
value = 420
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 70]) &&(p2bodydist y = [-80,5]) && P2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (125 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [210,219])|| (stateno = [240,249])||(stateno = [410,419])||(stateno = [440,449]))&& movehit&&var(55)
trigger2 = random < 600
;---------------------------------------------------------------------------
[State -1, Crouching Low Kick]
type = ChangeState
value = 430
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 35]) &&(p2bodydist y = [-50,25]) && P2statetype != A && P2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (50 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [200,209])|| (stateno = [400,409]))&& movehit&&var(55)
;---------------------------------------------------------------------------
[State -1, Crouching Medium Kick]
type = ChangeState
value = 440
triggerall = AILevel && numenemy && roundstate=2 && StateType != A
triggerall = (p2bodydist x = [0, 45]) &&(p2bodydist y = [-50,25]) && P2statetype != A && P2statetype != L && !(enemynear, hitfall)
trigger1 = ctrl && random < (75 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [210,219])|| (stateno = [230,239])||(stateno = [410,419])||(stateno = [430,439]))&& movehit&&var(55)
trigger2 = random < 350
;---------------------------------------------------------------------------
[State -1, Crouching High Kick]
type = ChangeState
value = 450
triggerall = AILevel && numenemy && roundstate=2 && StateType != A && P2statetype != A
triggerall = (p2bodydist x = [0, 55]) && (p2bodydist y = [ -50, 50]) && p2statetype != L && p2statetype = S && !(enemynear, hitfall)
trigger1 = ctrl && random < (100 * (AIlevel ** 2 / 64.0))
trigger2 = ((stateno = [220,229])|| (stateno = [240,249])||(stateno = [420,429])||(stateno = [440,449]))&& movehit&&var(55)
trigger2 = random < 900
;---------------------------------------------------------------------------
[State -1, Jumping Low Punch]
type = ChangeState
value = 600
triggerall = AILevel && numenemy&&roundstate=2&&statetype = A && (p2bodydist x = [0,60]) && (p2bodydist y = [ -50, 50]) && p2statetype != L
trigger1 = ctrl && random < (500 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, Jumping Medium Punch]
type = ChangeState
value = 610
triggerall = AILevel && numenemy&&roundstate=2&&statetype = A && (p2bodydist x = [0, 70]) && (p2bodydist y = [ -50, 50]) && p2statetype != L 
trigger1 = ctrl && random < (ifelse((vel x > 0 && p2statetype = A), 250, 125) * (AIlevel ** 2 / 64.0)) 
trigger2 = (stateno = [600,609])&& movehit && var(55)=2 && random < 750
trigger3 = (stateno = [630,639])&& movehit && var(55)=2 && random < 250
;---------------------------------------------------------------------------
[State -1, Jumping High Punch]
type = ChangeState
value = 620
triggerall = AILevel && numenemy&&roundstate=2&&statetype = A && (p2bodydist x = [0, 100]) && (p2bodydist y = [ -80, 50]) && p2statetype != L 
trigger1 = ctrl && random < (150 * (AIlevel ** 2 / 64.0)) && !(enemynear, hitfall)
trigger2 = (stateno = [610,619])&& movehit && var(55)=2 && random < 700
trigger3 = (stateno = [640,649])&& movehit && var(55)=2 && random < 200
;---------------------------------------------------------------------------
[State -1, Jumping Low Kick]
type = ChangeState
value = 630
triggerall = AILevel && numenemy&&roundstate=2&&statetype = A && (p2bodydist x = [0, 70]) && (p2bodydist y = [ -50, 50]) && p2statetype != L 
trigger1 = ctrl && random < (50 * (AIlevel ** 2 / 64.0))
trigger2 = (stateno = [600,609])&& movehit && var(55)=2 && random < 250
;---------------------------------------------------------------------------
[State -1, Jumping Medium Kick]
type = ChangeState
value = 640
triggerall = AILevel && numenemy&&roundstate=2&&statetype = A && (p2bodydist x = [0, 90]) && (p2bodydist y = [ -50, 50]) && p2statetype != L 
trigger1 = ctrl && random < (250 * (AIlevel ** 2 / 64.0)) && !(enemynear, hitfall)
trigger2 = (stateno = [610,619])&& movehit && var(55)=2 && random < 100
trigger3 = (stateno = [630,639])&& movehit && var(55)=2 && random < 750
;---------------------------------------------------------------------------
[State -1, Jumping High Kick]
type = ChangeState
value = 650
triggerall = AILevel && numenemy &&roundstate=2&&statetype = A && (p2bodydist x = [0, 130]) && (p2bodydist y = [ -50, 50]) && p2statetype != L 
trigger1 = ctrl && random < (250 * (AIlevel ** 2 / 64.0)) && !(enemynear, hitfall) 
trigger2 = (stateno = [610,619])&& movehit && var(55)=2 && random < 250
trigger3 = (stateno = [640,649])&& movehit && var(55)=2 && random < 750
;----------------------------------------------------------------------
[State -1, Red Hawk AI]
type = changestate
value=3000
triggerall=AILevel && numenemy && RoundState=2&& (stateno!=[3000,3001]) && StateType != A &&var(20)<=60&& power >= 1000 && random < (350 * (AIlevel ** 2 / 64.0))
triggerall=(p2stateno != [120, 155]) && (enemynear,statetype != L) && !(enemynear, hitfall)&&(enemynear,stateno!=[5100,5220]) &&(p2bodydist x =[50,100]) && (p2bodydist y =[-60,5]) &&(enemynear, statetype =S)
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])|| (StateNo=[110,111])
trigger2=var(6)|| var(7)
trigger3=(stateno=[200,450]) && movehit && random < (100 * (AIlevel ** 2 / 64.0))
;----------------------------------------------------------------------
[State -1, Gear 4 Strike AI]
type=changestate
value=3200
triggerall=AILevel && numenemy && RoundState=2 && StateType != A &&var(20)<=60&& power >= 3000 && random < (350 * (AIlevel ** 2 / 64.0))
triggerall=(enemynear,Movetype!=A)&&(enemynear,stateno!=[5100,5250])&&(enemynear,stateno!=[120,155])&&(enemynear,statetype!=A)&&(enemynear,statetype!=C)
triggerall=(p2stateno != [150, 155]) && (enemynear,statetype != L) && !(enemynear, hitfall)&&(enemynear,stateno!=[5100,5220]) && (P2dist x=[30,140])&&(P2dist y=[-80,5]) &&(enemynear, statetype != A)&&(enemynear, statetype != C)
trigger1=ctrl || StateNo=40 || StateNo=52 || (StateNo=[100,101])|| (StateNo=[110,111])
trigger2=var(6)&&enemynear,movetype=H&&random<400
trigger3=(stateno=[200,450]) && movehit && random < (100 * (AIlevel ** 2 / 64.0))
;----------------------------------------------------------------------
[State -1, Jet Gatling AI]
type = ChangeState
value=3100
triggerall=AILevel && numenemy && RoundState=2 && StateType != A &&var(20)<=60&& power >= 2000 && random < (100 * (AIlevel ** 2 / 64.0))
triggerAll = !(EnemyNear, ctrl) && ((EnemyNear, StateNo != [120,155]) || EnemyNear, StateType = A)
triggerAll = EnemyNear, StateType != L
triggerAll = (P2BodyDist x = [0,75]) && (P2Dist y = [-60,0])
trigger1 = (ctrl || StateNo = 52 || (StateNo = [100,101])) && Random < (100 * (AILevel ** 2 / 64.0))
trigger2=var(6)|| var(7)
trigger3=(stateno=[200,450]) && movehit && random < (100 * (AIlevel ** 2 / 64.0))
;----------------------------------------------------------------------
[State -1, Elephant Gatling AI]
type = ChangeState
value=3300
triggerall=AILevel && numenemy && RoundState=2 && StateType != A &&var(20)<=60&& power >= 2000 && random < (100 * (AIlevel ** 2 / 64.0))
triggerAll = !(EnemyNear, ctrl) && ((EnemyNear, StateNo != [120,155]) || EnemyNear, StateType = A)
triggerAll = EnemyNear, StateType != L
triggerAll = (P2BodyDist x = [0,75]) && (P2Dist y = [-60,0])
trigger1 = (ctrl || StateNo = 52 || (StateNo = [100,101])) && Random < (100 * (AILevel ** 2 / 64.0))
trigger2=var(6)|| var(7)
trigger3=(stateno=[200,450]) && movehit && random < (100 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, Storm AI]
type = ChangeState
value = ifElse(Power >= 500 && Random < 100 && (P2BodyDist x = [0,145]), 1051, 1050)
triggerall=AILevel && RoundState=2 && numenemy && StateType != A && var(20)<=60 
triggerAll = (P2BodyDist x = [0,185]) && P2StateType != L
triggerAll = (EnemyNear, const(size.head.pos.y) <= -40) || (EnemyNear, StateType = A)
trigger1 = (ctrl || StateNo = 52 || (StateNo = [100,101])) && Random < (50 * (AILevel ** 2 / 64.0))
trigger2 = var(5) && MoveContact && Random < (100 * (AILevel ** 2 / 64.0))
trigger3 = (stateno = [200, 250]) && (movehit = [1, 16]) && random < (150 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, Elephant Gun AI]
type=ChangeState
value=Ifelse((power >= 200 && random < 100), 1010, 1000)
triggerall=AILevel && numenemy && RoundState=2 && StateType != A &&var(20)<=60 && random < (250 * (AIlevel ** 2 / 64.0))
triggerall=(p2stateno != [120, 155]) && (enemynear,statetype != L)&&(enemynear,stateno!=[5100,5220]) && p2bodydist x >=10 && p2bodydist x <=70 &&(p2dist y=[-110,5]) &&(enemynear, statetype != C)
trigger1=ctrl || (StateNo=[100,101])|| (StateNo=[110,111])
trigger2=var(5)
trigger3=(stateno=[200,440])&&movehit&&random<200
;---------------------------------------------------------------------------
[State -1, Jet Pistol AI]
type = ChangeState
value = ifElse(Power >= 500 && Random < 100 && (P2BodyDist x = [0,145]), 1025, 1020)
triggerall=AILevel && RoundState=2 && numenemy && StateType != A && var(20)<=60 
triggerAll = (P2BodyDist x = [0,185]) && P2StateType != L
triggerAll = (EnemyNear, const(size.head.pos.y) <= -40) || (EnemyNear, StateType = A)
trigger1 = (ctrl || StateNo = 52 || (StateNo = [100,101])) && Random < (50 * (AILevel ** 2 / 64.0))
trigger2 = var(5) && MoveContact && Random < (100 * (AILevel ** 2 / 64.0))
trigger3 = (stateno = [200, 250]) && (movehit = [1, 16]) && random < (150 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, Jet Bazooka AI]
type = ChangeState
value = ifElse(Power >= 500 && Random < 100 && (P2BodyDist x = [0,145]), 1035, 1030)
triggerall=AILevel && RoundState=2 && numenemy && StateType != A && var(20)<=60 
triggerAll = (P2BodyDist x = [0,185]) && P2StateType != L
triggerAll = (EnemyNear, const(size.head.pos.y) <= -40) || (EnemyNear, StateType = A)
trigger1 = (ctrl || StateNo = 52 || (StateNo = [100,101])) && Random < (50 * (AILevel ** 2 / 64.0))
trigger2 = var(5) && MoveContact && Random < (100 * (AILevel ** 2 / 64.0))
trigger3 = (stateno = [200, 250]) && (movehit = [1, 16]) && random < (150 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, Ono Kick]
type=ChangeState
value=Ifelse((power >= 500 && random < 75), 1040, 1040)
triggerall=AILevel && RoundState=2 && numenemy && StateType != A && var(20)<=60 
triggerall=(enemynear,statetype != L) && !(enemynear, hitfall) && (enemynear,stateno!=[5100,5220]) && (p2bodydist x =[30,120]) && (p2bodydist y =[-80,5]) && (enemynear, statetype != C) 
trigger1=(ctrl || StateNo=40 || StateNo=52 ||(StateNo=[110,111])||(StateNo=[100,101]))&& random < (150 * (AIlevel ** 2 / 64.0))
trigger2=var(5) && movehit  && random<100
trigger3=(stateno=[200,450]) && movehit && random < (500 * (AIlevel ** 2 / 64.0))
;---------------------------------------------------------------------------
[State -1, run]
type = changestate
value = 100
trigger1 = AIlevel && numenemy
trigger1 = statetype = S && roundstate = 2 && ctrl && random < (300 * (AIlevel ** 2 / 64.0))
trigger1 = (stateno != [100, 105]) && enemynear, movetype != A && p2bodydist x > 120

[State -1, dash]
type = changestate
value = 105
triggerall = AIlevel && numenemy
triggerall = statetype = S && roundstate = 2 && ctrl
triggerall = (p2bodydist x = [0, 80]) && backedgebodydist > 80 && (stateno != [100, 105])
trigger1 = enemynear, movetype = A && random < (50 * (AIlevel ** 2 / 64.0))
trigger2 = enemynear, stateno = 5120 && enemynear, animtime = -3 && random < (300 * (AIlevel ** 2 / 64.0))

[State -1, Jump]
type = changestate
value = 40
triggerall = AIlevel && numenemy&&random < (50 * (AIlevel ** 2 / 64.0))
triggerall = roundstate = 2 && statetype != A
triggerall = enemynear, movetype = A && p2bodydist x < 160 && enemynear, hitdefattr = SC, AT
trigger1=ctrl

[state -1,AI Air Guard]
type = ChangeState
value = 132
triggerall = AIlevel && numenemy&& roundstate = 2&&InGuardDist
triggerall = ctrl&&statetype = A
trigger1 = enemynear,numproj
trigger2 = enemynear,HitDefAttr = SCA, NA,SA,HA
trigger2 = random <=ifelse(backedgedist<=10,900,700)

[State -1, Guard]
type = changestate
value = 120
trigger1 = AIlevel && numenemy
trigger1 = roundstate = 2 && inguarddist
trigger1 = ctrl && (stateno != [120, 155]) && !var(20)
trigger1 = !(enemynear, hitdefattr = SCA, AT) && (enemynear, time < 120)
trigger1 = statetype != A || p2statetype = A
trigger1 = random < (ifelse((p2stateno = [200, 699]), 300, ifelse((p2stateno = [1000, 2999]), 500, 1000)) * (AIlevel ** 2 / 64.0))

[State -1, Guard]
type = ChangeState
value = 120
triggerall= AILevel && numenemy&& (StateNo!=[120,155]) && !(enemynear,ctrl) && random < (450 * (AIlevel ** 2 / 64.0))
triggerall= Ctrl||stateno = 21
triggerall=enemynear,Movetype=A && !(enemynear,hitdefattr=SCA,AT) 
trigger1 = inguarddist

[State -1, Super Jump]
type = ChangeState
value = 123
triggerall = AILevel && numenemy && var(55)=2 && statetype != A && roundstate = 2 && (p2bodydist y = [-320,5])
triggerall = stateno != 100 && pos y = 0 && (enemynear,Statetype!=C)
trigger1 = ctrl && enemy,vel y < -1 && (p2bodydist x = [ 10, 70]) && enemynear,movetype != A && random < (200 * (AIlevel ** 2 / 64.0))
trigger2 = ctrl && enemy,vel y < -1 && random < (150 * (AIlevel ** 2 / 64.0))
trigger2 = enemynear,movetype = H && (enemynear,stateno=5040)
trigger2 = p2bodydist x <= 50 && random < (150 * (AIlevel ** 2 / 64.0))
trigger3 = ctrl && enemynear,MoveType != H&&P2BodyDist Y < -90&& enemy,vel y <= 0 && random < (350 * (AIlevel ** 2 / 64.0))
trigger4 = stateno=420 && anim=425 && MoveHit && random < (800 * (AIlevel ** 2 / 64.0))
trigger5 = ctrl && (p2bodydist x<=140) && (enemynear,statetype!=A) && (enemynear,movetype=A) && (enemynear,stateno=[2000,4999]) && random < (750 * (AIlevel ** 2 / 64.0))

[State -1, Zero Counter]
type = changestate
value = 750
trigger1 = AIlevel && numenemy
trigger1 = (p2dist x = [-90, 90]) && stateno = 150 || stateno = 152
trigger1 = roundstate = 2 && power >= 2000 && !var(20) && life < 500 && random < (10 * (AIlevel ** 2 / 64.0))

[State -1, powercharge]
type = changestate
value = 730
trigger1 = AIlevel && numenemy
trigger1 = !numhelper(3033)
trigger1 = roundstate = 2 && statetype != A && ctrl
trigger1 = power < const(data.power) && power < powermax && !var(20)
trigger1 = random < (50 * (AIlevel ** 2 / 64.0)) && !inguarddist && p2movetype != A && p2dist x >= 160

[State -1, roll / dodge]
type = changestate
value = ifelse(random < 600, 700, 710)
trigger1 = AIlevel && numenemy
trigger1 = roundstate = 2 && statetype != A && ctrl && random < (200 * (AIlevel ** 2 / 64.0))
trigger1 = enemynear, movetype = A && p2bodydist x < 80

[State -1, airrecover]
type=changestate
value=ifelse((pos y>=-20),5200,5210)
triggerall= AILevel && numenemy
triggerall= roundstate=2 && stateno=5050
trigger1= vel y>-1 && alive && canrecover && random < (350 * (AIlevel ** 2 / 64.0))

